### ISSUE TITLE
GIT Clone steps in Instructions refer to old repository name

### ISSUE THREAD

**Issue by TesterTesterson1004** [MicrosoftLearning/AI-102-AIEngineer.ja-jp#1]
# Module: (all)
#### Step: 00

Description of issue

The GIT Clone steps in the lab steps refer to the old repository name, and should be updated to point to this new repository:

パレットを開き (SHIFT+CTRL+P)、Git: Clone コマンドを実行して、https://github.com/MicrosoftLearning/AI-102JA-Designing-and-Implementing-a-Microsoft-Azure-AI-Solution リポジトリをローカル フォルダーに複製します (どのフォルダーでもかまいません)。

**Comment by olprod** [comment]
Hello contributor,

Thank you for your contribution! We are processing your suggestions and we will update you shortly.   

Kind regards,  

Microsoft Worldwide Learning Team

**Comment by Chenpeng21** [comment]
This issue can no longer be reproduced.
![image](https://user-images.githubusercontent.com/93902755/181458584-f4ee8ef1-312f-4d14-950f-2fb4b00cc8cc.png)
