### ISSUE TITLE
Modify Azure portal url Cross AI-102-AIEngineer.ja-jp

### ISSUE THREAD

**Issue by chriscarty00** [MicrosoftLearning/AI-102-AIEngineer.ja-jp#9]
Description : 
Cross AI-102-AIEngineer.ja-jp can Azure portal url be changed from 

https://portal.azure.com
to
https://portal.azure.com/?l=ja.ja-jp

This would need to be updated in all files under the instructions folder

If taken it would need to be done for all langs 

Perhaps is this something that could be fixed via a redirect DB 

Referring to WWL PM 

Sample 

![image](https://github.com/MicrosoftLearning/AI-102-AIEngineer.ja-jp/assets/63402128/e70e6124-e481-4e88-96b5-cc13bf058b72)

**Comment by stonezy123** [comment]
This is by-design. because when you open the Azure portal, you can change the language.
